import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
    },
    headerText: {
      fontSize: theme.size.xLarge,
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'center',
      marginVertical: hp(8),
    },
    profileContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      alignItems: 'center',
    },
    imgStyle: {
      height: hp(12),
      width: hp(12),
      borderRadius: hp(10),
      borderWidth: hp(0.001),
      alignSelf: 'center',
      backgroundColor: theme.color.textBlack,
      // padding: 20,
    },
    slider: {
      backgroundColor: 'red',
    },
    headerContainerStyle: {
      borderBottomColor: 'transparent',
      backgroundColor: 'transparent',
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    nameContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
    },
    subscriptionCard: {
      flex: 1,
      margin: 10,
      width: '95%',
      height: hp('32'),
      alignSelf: 'center',
      // flexDirection: 'row',
      borderRadius: hp(2),
      borderWidth: hp('0.1'),
      backgroundColor: theme.color.textWhite,
      // borderBottomWidth: hp('0.1'),
      borderColor: theme.color.dividerColor,
    },
    title: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textBlack,
    },
    textFieldTitle: {
      fontSize: theme.size.medium,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
    },
    nameText: {
      fontSize: hp(2.2),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.semiBoldFamily,
      paddingLeft: hp(3),
    },
    mapContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      borderRadius: hp(2),
      overflow: 'hidden',
      marginLeft: hp(2.5),
      marginTop: hp(2.5),
      marginBottom: hp(5),
    },

    map: {
      width: wp(88),
      height: hp(28),
    },
    emailText: {
      fontSize: hp(1.7),
      color: theme.color.textGray,
      paddingLeft: hp(3),
      paddingBottom: hp(2),
    },
    subContainer: {
      height: hp(14),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(0.5),
      alignItems: 'center',
      paddingBottom: hp(2),
      borderBottomWidth: hp(0.1),
      borderColor: 'transparent',
      marginTop: -hp(4),
    },
    headerColor: 'headerColor',
    container: {
      marginTop: hp(1.5),

      flexGrow: 1,
      // paddingLeft: hp(3),
      paddingRight: hp(3),
      // paddingBottom: hp(5),
      backgroundColor: theme.color.textWhite,
      // justifyContent: 'center',
      alignItems: 'flex-start',
    },
    statusBar: {
      backgroundColor: 'transparent',
    },
    cancelModalButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: theme.color.dividerColor,
    },
    modalText: {
      color: theme.color.textWhite,
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
    },
    acceptModalButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: 'red',
    },
    responseText: {
      marginTop: hp(3),
      marginBottom: hp(3),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    thumbStyle: {
      height: hp(11),
      width: hp(11),
      borderRadius: hp(16),
      // borderWidth: hp(0.75),
      alignSelf: 'center',
      // borderColor: '#3DB249',
      // backgroundColor: '#3DB249',
      // padding: 20,
    },
    dashStyle: {
      fontSize: theme.size.medium,
      color: theme.color.dividerColor,
      alignSelf: 'center',
      marginTop: hp(2),
      marginBottom: hp(2),
    },

    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
      marginLeft: hp(1),
      backgroundColor: theme.color.textWhite,
    },
    loginSubText: {
      fontSize: theme.size.small,
      alignSelf: 'center',
      textAlign: 'center',
    },
    checkBoxText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: '#748B9B',
      paddingLeft: hp(1),
      marginTop: hp(0.5),
    },
    otpView: {
      width: '80%',
      height: hp(20),
      color: theme.color.textBlack,
    },

    optContainer: {
      flexGrow: 1,
      justifyContent: 'space-between',
    },
    viewProfile: {
      width: hp(15),
      height: hp(4.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      marginVertical: hp(1),
    },
    viewProfileText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textWhite,

      // marginHorizontal: wp(2),
    },
  });
  return styles;
};
export default createStyles;
