import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
    },
    headerText: {
      fontSize: theme.size.xLarge,
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'center',
      marginVertical: hp(8),
    },
    slider: {
      backgroundColor: 'red',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
      height: hp(15),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    subscriptionCard: {
      flex: 1,
      margin: 10,
      width: '95%',
      height: hp('32'),
      alignSelf: 'center',
      borderRadius: hp(2),
      borderWidth: hp('0.1'),
      backgroundColor: theme.color.textWhite,
      borderColor: theme.color.dividerColor,
    },
    categoryTitle: {
      marginBottom: wp(1),
      fontSize: theme.size.xsmall,
      textAlign: 'left',
      paddingLeft: hp(1),
    },
    textFieldTitle: {
      fontSize: theme.size.medium,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
    },
    priceText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      paddingLeft: hp(0.5),
    },
    headerInitialText: {
      alignSelf: 'center',
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    subContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(3),
      alignItems: 'center',
      paddingBottom: hp(2),
      marginLeft: hp(1),
    },
    responseText: {
      marginTop: hp(3),
      marginBottom: hp(3),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    okButtonText: {
      fontFamily: theme.fontFamily.mediumFamily,
      fontSize: hp(2),
      color: theme.color.textWhite,
    },
    headerColor: theme.color.textWhite,
    container: {
      flexGrow: 1,
      backgroundColor: theme.color.textWhite,
      justifyContent: 'space-between',
    },
    inviteButton: {
      marginTop: 20,
      width: wp(85),
      height: hp(7),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textBlack,
    },
    inviteText: {
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      fontSize: theme.size.xsmall,
    },
    cancelJobButton: {
      marginTop: 20,
      marginBottom: hp(3),
      width: wp(85),
      height: hp(7),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textRed,
    },

    inviteText: {
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      fontSize: theme.size.xsmall,
    },
    rejectButton: {
      marginTop: 20,
      width: wp(85),
      height: hp(7),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textWhite,
    },
    rejectText: {
      color: theme.color.textRed,
      fontFamily: theme.fontFamily.boldFamily,
      fontSize: theme.size.xsmall,
    },

    responseButtonText: {
      color: theme.color.textWhite,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },

    responseText: {
      marginTop: hp(2),
      marginBottom: hp(3),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    modalTitle: {
      zIndex: 101,
      color: theme.color.textBlack,
      alignSelf: 'center',
      borderBottomWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
      paddingBottom: hp(2),
      marginBottom: hp(2),
      width: hp(45),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingRight: hp(1),
      paddingHorizontal: hp(2),
    },
    submitText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textWhite,
    },
    optionText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
    },
    loggingText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.mediumFamily,
      alignSelf: 'center',
    },
    termsText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textBlack,
    },
    checkboxContainer: {
      flexDirection: 'row',
      marginBottom: hp(2.5),
      marginTop: -hp(1),
      marginLeft: -hp(1),
    },

    submitButton: {
      flexGrow: 1,
      width: hp(37),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textBlack,
    },
    proposalInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      marginLeft: -hp(2),
      borderBottomWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
    },
    proposalTitle: {
      fontSize: hp(2.2),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      marginLeft: -hp(0.5),
    },
    applyTitle: {
      fontSize: hp(2.6),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      marginLeft: hp(0.5),
    },
    thumbStyle: {
      height: hp(11),
      width: hp(11),
      borderRadius: hp(16),
      alignSelf: 'center',
      // padding: 20,
    },
    cancelModalButton: {
      width: wp(35),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: theme.color.dividerColor,
    },
    acceptModalButton: {
      width: wp(35),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: 'red',
    },
    responseButton: {
      width: hp(22),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
    },
    ProposalText: {
      fontSize: hp(2),
      // paddingLeft: hp(1),
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'left',
      marginBottom: -hp(2),
    },
    listStyle: {
      // margin: 10,
      width: '95%',
      height: hp(10),
      alignSelf: 'flex-start',
      // backgroundColor: 'red',

      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
      paddingLeft: hp(1.5),
      borderColor: 'white',
    },
    cardStyle: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      marginRight: '10%',
      marginLeft: -hp(3),
      marginTop: -hp(3),
    },
    dashStyle: {
      fontSize: theme.size.medium,
      color: theme.color.textGray,
      alignSelf: 'center',
      marginTop: hp(2),
      marginBottom: hp(2),
    },

    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
    },
    loginSubText: {
      fontSize: theme.size.small,
      alignSelf: 'center',
      textAlign: 'center',
    },
    checkBoxText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: '#748B9B',
      paddingLeft: hp(1),
      marginTop: hp(0.5),
    },
    qrDescriptionText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textGray,
      paddingLeft: hp(1),
      marginTop: hp(1),
      alignSelf: 'center',
      textAlign: 'center',
    },

    profileText: {
      color: 'white',
    },
    otpView: {
      width: '80%',
      height: hp(20),
      color: theme.color.textBlack,
    },

    optContainer: {
      flexGrow: 1,
      justifyContent: 'space-between',
    },
    subscriptionButton: {
      width: hp(40),
      height: hp(6.5),
      borderRadius: hp(1),
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      marginTop: hp(10),
    },
    subsText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,

      // marginHorizontal: wp(2),
    },
    nameContainer: {
      paddingTop: hp(0.5),
      paddingHorizontal: hp(2),
      marginBottom: hp(1),
      justifyContent: 'space-between',
      flexDirection: 'row',
    },
    titleContainer: {
      marginLeft: hp('1'),
      width: wp(40),
    },

    skillsText: {
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textGray,
    },
    nameText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textGray,
      paddingLeft: hp(0.5),
    },
    title: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textBlack,
    },
    qrImageStyle: {
      width: hp(30),
      height: hp(30),
      alignSelf: 'center',
      marginTop: hp(2),
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageStyle: {
      width: wp(15),
      height: hp(8),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: hp(1.5),
      flexDirection: 'row',
    },
    priceText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textBlack,
    },
    jobDescriptionText: {
      fontSize: theme.size?.medium,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      paddingLeft: hp(2),
    },
    qrTitleText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      paddingLeft: hp(2),
      marginTop: hp(2),
    },
    listItem: {
      flex: 1,
      width: '95%',
      alignSelf: 'center',
      backgroundColor: theme.color.textWhite,
    },
    header: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      padding: hp(1),
      marginBottom: hp(0.5),
    },
    iconView: {
      backgroundColor: theme.color.textBlack,
      width: wp(12),
      height: hp(6),
      borderRadius: hp(10),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.29,
      shadowRadius: 4.65,

      elevation: 7,
    },
    checkbox: {marginTop: -hp(0.5), marginLeft: -hp(0.3)},
    checkBoxText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textGray,
      paddingLeft: hp(2),
      marginTop: hp(2),
    },
    imgStyle: {
      width: wp(15),
      height: wp(15),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: hp(1.5),
      flexDirection: 'row',
    },
    progressJobButton: {
      width: hp(14),
      height: hp(4.5),
      // marginRight: hp(5),
      borderRadius: hp(1),
      justifyContent: 'center',
      marginTop: hp(2),
      alignItems: 'center',
      borderWidth: hp(0.03),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textWhite,
      alignSelf: 'flex-end',
    },
    headerPriceContainer: {
      flexDirection: 'column',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
    },
    profileText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      textTransform: 'capitalize',
    },
    priceView: {
      justifyContent: 'flex-start',
    },
    jobDescriptionView: {
      marginTop: hp(2),
    },

    postedByView: {
      marginHorizontal: wp(3),
      marginBottom: hp(2),
    },
    postedByImg: {
      borderRadius: wp(10),
      backgroundColor: theme.color.dividerColor,
    },
    postedImageStyle: {
      width: wp(12),
      height: wp(12),

      borderRadius: wp(10),
    },
    postedByInnerView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: hp(2),
    },
    postedByInnerText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      marginLeft: wp(2),
    },
    postedByText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textGray,
    },
  });
  return styles;
};
export default createStyles;
