import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    scrollViewStyle: {
      // backgroundColor: 'yellow',
      marginTop: hp(3),
      marginBottom: hp(6),
    },
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },
    inputContainer: {
      flexGrow: 1,
      marginTop: hp(3),
    },
    headerText: {
      fontSize: theme.size.xLarge,
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'center',
      marginVertical: hp(8),
    },
    profileContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      alignItems: 'center',
    },
    imgStyle: {
      height: hp(12),
      width: hp(12),
      borderRadius: hp(10),
      borderWidth: hp(0.001),
      alignSelf: 'center',
      backgroundColor: theme.color.textBlack,
      // padding: 20,
    },
    slider: {
      backgroundColor: 'red',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    nameContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      paddingTop: hp(3),
    },
    subscriptionCard: {
      flex: 1,
      margin: 10,
      width: '95%',
      height: hp('32'),
      alignSelf: 'center',
      // flexDirection: 'row',
      borderRadius: hp(2),
      borderWidth: hp('0.1'),
      backgroundColor: theme.color.textWhite,
      // borderBottomWidth: hp('0.1'),
      borderColor: theme.color.dividerColor,
    },
    title: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.textBlack,
    },
    textFieldTitle: {
      fontSize: theme.size.medium,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
      marginTop: hp(1),
    },
    nameText: {
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    emailText: {
      fontSize: hp(1.7),
    },
    subContainer: {
      height: hp(16),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(0.5),
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerColor: theme.color.textWhite,
    container: {
      marginTop: hp(1.5),

      flexGrow: 1,
      paddingLeft: hp(3),
      paddingRight: hp(3),
      // paddingBottom: hp(5),
      backgroundColor: theme.color.textWhite,
      justifyContent: 'center',
    },
    cancelModalButton: {
      width: wp(35),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: theme.color.dividerColor,
    },
    modalText: {
      color: theme.color.textWhite,
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
    },
    acceptModalButton: {
      width: wp(35),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: 'red',
    },
    responseText: {
      marginTop: hp(3),
      marginBottom: hp(3),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    thumbStyle: {
      height: hp(11),
      width: hp(11),
      borderRadius: hp(16),
      // borderWidth: hp(0.75),
      alignSelf: 'center',
      // borderColor: '#3DB249',
      // backgroundColor: '#3DB249',
      // padding: 20,
    },
    dashStyle: {
      fontSize: theme.size.medium,
      color: theme.color.dividerColor,
      alignSelf: 'center',
      marginTop: hp(2),
      marginBottom: hp(2),
    },

    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
      marginTop: hp(1),
    },
    loginSubText: {
      fontSize: theme.size.small,
      alignSelf: 'center',
      textAlign: 'center',
    },
    checkBoxText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: '#748B9B',
      paddingLeft: hp(1),
      marginTop: hp(0.5),
    },
    otpView: {
      width: '80%',
      height: hp(20),
      color: theme.color.textBlack,
    },

    optContainer: {
      flexGrow: 1,
      justifyContent: 'space-between',
    },
    viewProfile: {
      width: hp(15),
      height: hp(4.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      marginVertical: hp(1),
    },
    viewProfileText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.textWhite,

      // marginHorizontal: wp(2),
    },
    listItemIconView: {
      width: wp(9),
      height: wp(9),
      backgroundColor: '#e6e6e6',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: wp(6),
    },
    arrowRightView: {},

    listItem: {
      width: wp(92),
      height: hp(8),
      alignSelf: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.color.textWhite,
      alignItems: 'center',
      flexDirection: 'row',
      borderRadius: hp(2.5),
      paddingLeft: hp(1.5),
      borderWidth: hp('0.1'),
      paddingRight: hp(2),
      borderColor: theme.color.dividerColor,
      marginBottom: hp(1.3),
    },
    modalTitle: {
      zIndex: 101,
      color: theme.color.textBlack,
      alignSelf: 'center',
      borderBottomWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
      paddingBottom: hp(2),
      marginBottom: hp(2),
      width: hp(40),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    SkillsTitle: {
      fontSize: hp(2.6),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      marginLeft: hp(1.4),
    },
    selectedSkillsView: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    dialogStyle: {justifyContent: 'center', alignItems: 'center'},
    updateButton: {
      flexGrow: 1,
      width: wp(75),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      marginTop: hp(3),
      backgroundColor: theme.color.textBlack,
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    responseButton: {
      width: hp(22),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
    },
    updateButtonText: {
      color: theme.color.textWhite,
      fontFamily: theme.fontFamily.boldFamily,
      fontSize: theme.size.small,
    },

    cancelSkill: {
      position: 'absolute',
      right: wp(2),
    },
    selectedSkillsItemText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.dividerColor,
      textTransform: 'capitalize',
    },
    selectedSkillsItem: {
      // alignItems: 'flex-start',
      marginRight: wp(3),
      marginBottom: wp(3),
      backgroundColor: '#F8F8F8',
      width: wp(27),
      height: hp(6),
      justifyContent: 'space-between',
      paddingLeft: wp(2),
      alignItems: 'center',
      flexDirection: 'row',
      borderRadius: wp(5),
      borderWidth: 1,
      borderColor: theme.color.dividerColor,
    },
    categoryText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      paddingLeft: wp(1),
    },
    errorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
    },
    dropdownStyle: {
      marginBottom: hp(1),
    },
    webModal: {
      paddingTop: hp(8),
      paddingBottom: hp(4),
    },
  });
  return styles;
};
export default createStyles;
