import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
      flexGrow: 1,
    },
    subContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: hp(2),
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerInitialText: {
      alignSelf: 'center',
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignContent: 'center',
    },
    headerLastText: {
      fontSize: theme.size.xLarge,
      color: theme.color.backgroundColor,
      textAlign: 'center',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
      height: hp(15),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerColor: theme.color.textWhite,
    addMemoryIcon: theme.color.backgroundColor,
    container: {
      paddingHorizontal: hp(7),
      paddingBottom: hp(5),
      alignItems: 'center',
    },
    homeText: {
      fontSize: theme.size.large,
    },
    dropDownStyle: {
      paddingLeft: hp(1),
      borderColor: theme.color.textWhite,
      borderBottomWidth: hp(0.12),
      borderLeftWidth: 0,
      borderRightWidth: 0,
      borderBottomColor: theme.color.dividerColor,
      marginBottom: hp(1),
      width: wp(88),
      marginHorizontal: wp(1.5),
    },
    addressTouchField: {
      borderWidth: 1,
      borderColor: 'transparent',
      borderBottomColor: theme.color.dividerColor,
      marginHorizontal: wp(2),
      height: hp(4),
      marginTop: hp(2),
    },
    addressInputField: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    addressPlaceholder: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      color: theme.color.dividerColor,
    },
    saveChangesButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      // padding: hp(2.75),
      width: wp(50),
      height: hp(6.5),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
    },

    saveChangesButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
    },
    textFieldTitle: {
      fontSize: theme.size.medium,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      marginTop: hp(1),
      fontFamily: theme.fontFamily.boldFamily,
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    inputStyle: {
      height: hp(8),
      textAlignVertical: 'bottom',
    },
    containerStyle: {
      height: hp(8),
    },
    socialSecurityText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      // marginBottom: hp(7),
      borderBottomColor: theme.color.dividerColor,
      borderBottomWidth: hp(0.1),
    },

    avatarImage: {marginTop: hp(7), marginRight: wp(5)},
    memoryContainer: {
      marginTop: hp(2),
      marginHorizontal: hp(7),
    },
    profileImage: {
      marginRight: wp(5),
      marginBottom: hp(3),
    },
    firstMemoryText: {
      fontSize: theme.size.medium,
      paddingBottom: hp(2),
    },
    dialogStyle: {
      backgroundColor: 'white',
      height: hp(45),
      width: wp(60),
      alignSelf: 'center',
    },
    errorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: hp(0.5),
    },
    socialErrorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(1),
    },
    otherErrorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
    },
    dropdownError: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(2),
      marginBottom: hp(0.5),
    },
    aboutError: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
    },
    errorUploadIDText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(1.5),
    },
    errorSSNText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(3.5),
      marginBottom: hp(7),
    },
    contentStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    profileButton: {
      margin: hp(1),
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: wp(40),
      height: hp(6),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.headerBackgroundColor,
    },
    iconHeaderContainer: {width: '10%', paddingLeft: hp(1)},
    headerTitleContainer: {
      flexDirection: 'row',
      width: '90%',
      alignSelf: 'center',
      justifyContent: 'center',
      alignContent: 'center',
    },
    inputContainer: {
      flexGrow: 1,
      height: hp(75),
    },
    loginButton: {
      width: hp(45),
      height: hp(6.5),
      borderRadius: hp(1),
      alignSelf: 'flex-end',
      justifyContent: 'center',
      marginTop: hp(5),
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      // position: 'absolute',
      // bottom: 0,
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    topRadioSlider: {
      backgroundColor: theme.color.black,
      height: hp(5),
    },
    nextButtonStyle: {
      width: wp(85),
      height: hp(7),
      borderRadius: hp(1),
      // alignSelf: 'center',
      marginRight: -wp(7.5),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      marginTop: hp(5),
    },
    nextButtonTextStyle: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    nextButtonStyle2: {
      width: wp(35),
      height: hp(7),
      borderRadius: hp(1),
      // alignSelf: 'center',
      marginRight: -wp(7),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
      zIndex: -1,
    },
    nextButtonTextStyle2: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    prevButtonStyle: {
      width: wp(35),
      height: hp(7),
      borderRadius: hp(1),
      marginLeft: -wp(7),
      // alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.3),
      borderColor: theme.color.black,
      zIndex: -1,
      // backgroundColor: theme.color.textBlack,
    },
    prevButtonTextStyle: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
    },

    otherInfoProgressView: {
      width: wp(90),
      alignSelf: 'center',
      marginTop: hp(5),
      height: hp(50),
    },
    socialProgressView: {
      width: wp(90),
      height: hp(55),
      alignSelf: 'center',
      paddingTop: hp(2),
    },
    uploadIdView: {
      height: hp(30),
      width: wp(85),
      borderWidth: 1,
      borderStyle: 'dashed',
      borderRadius: wp(5),
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: hp(5),
      marginHorizontal: wp(3),
      marginTop: hp(1),
      marginBottom: hp(2),
      backgroundColor: '#F8F8F8',
      // backgroundColor: theme.color.dividerColor,
    },
    uplaodIdText: {
      // backgroundColor: 'red',
      paddingTop: hp(3),
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.dividerColor,
    },
    selectedSkillsView: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    selectedSkillsItem: {
      // alignItems: 'flex-start',
      marginRight: wp(3),
      marginBottom: wp(3),
      backgroundColor: '#F8F8F8',
      width: wp(27),
      height: hp(6),
      justifyContent: 'space-between',
      paddingLeft: wp(2),
      alignItems: 'center',
      flexDirection: 'row',
      borderRadius: wp(5),
      borderWidth: 1,
      borderColor: theme.color.dividerColor,
    },
    cancelSkill: {
      position: 'absolute',
      right: wp(2),
    },
    selectedSkillsItemText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.boldFamily,
      color: theme.color.dividerColor,
      textTransform: 'capitalize',
    },
  });
  return styles;
};
export default createStyles;
